/** Sample content pool. Depth A: 孕晚–1岁细稿样例；孕早中与 1–7 岁为骨架。无剂量/处方。 */

export const PRESET_TAGS = [
  { id: "vax-watch", name: "疫苗后观察", defaultDays: 5, hint: "观察类科普（免责）；推迟强运动技能" },
  { id: "travel", name: "回老家 / 出行", defaultDays: 7, hint: "推迟本地线下事项" },
  { id: "hospital", name: "住院待产", defaultDays: 5, hint: "入院清单优先" },
  { id: "grandparents", name: "隔代来住", defaultDays: 14, hint: "交接与协同" },
  { id: "nanny-end", name: "月嫂结束", defaultDays: 10, hint: "自己上手过渡" },
  { id: "less-volume", name: "想降量", defaultDays: 2, hint: "合并后更短" },
];

export const CARE_MODES = [
  { id: "parents", label: "父母自带" },
  { id: "grandparents", label: "隔代" },
  { id: "mixed", label: "托育+家庭" },
];

export const WORK_STATUSES = [
  { id: "working", label: "在岗" },
  { id: "maternity", label: "产假" },
  { id: "paternity", label: "陪产假" },
  { id: "lactation", label: "哺乳假" },
  { id: "returned", label: "已返岗" },
];

/**
 * anchor:
 *  - { kind: "gestWeek", n }  预产期按 40 周倒推
 *  - { kind: "ageMonths", n } 生日（未出生则用预产期作预期生日）起第 n 个整月
 *  - { kind: "ageYears", n }
 *  - { kind: "dueOffsetDays", n } 相对预产期/生日的天数
 * region: "all" | "shanghai" | "other"
 * depth: "detailed" | "skeleton"
 */
export const CATALOG = [
  // —— 孕早（骨架）——
  {
    id: "e1-f",
    title: "何时开始学待产（入口）",
    role: "father",
    type: "skill",
    depth: "skeleton",
    stage: "孕早期",
    stageGroup: "early",
    region: "all",
    anchor: { kind: "gestWeek", n: 12 },
    whyNow: "孕早期只需知道「待产技能会在孕晚展开」，现在不用学完。",
    body: "骨架：孕晚会有待产包、入院陪同等细步骤。现在记下入口即可。以后会加细。",
    steps: [],
  },
  {
    id: "e1-m",
    title: "何时开始学待产（入口）",
    role: "mother",
    type: "skill",
    depth: "skeleton",
    stage: "孕早期",
    stageGroup: "early",
    region: "all",
    anchor: { kind: "gestWeek", n: 12 },
    whyNow: "孕早期只需知道「待产技能会在孕晚展开」，现在不用学完。",
    body: "骨架：呼吸/用力认知、待产包使用会在孕晚写成可勾选步骤。现在只需知道有这么一门。以后会加细。",
    steps: [],
  },
  {
    id: "e2-m",
    title: "建档 / 产检窗口",
    role: "mother",
    type: "other",
    depth: "skeleton",
    stage: "孕早期",
    stageGroup: "early",
    region: "all",
    anchor: { kind: "gestWeek", n: 8 },
    whyNow: "建档窗口通常早于系统产检高峰，T0 取窗口下限。",
    body: "骨架：存在「建档/首次产检」窗口。上海用户以社区/医院通知为准；其他地区以当地社区/医院为准，不写死外地截止日期。",
    steps: [],
  },
  {
    id: "e2-f",
    title: "陪同建档的材料意识",
    role: "father",
    type: "other",
    depth: "skeleton",
    stage: "孕早期",
    stageGroup: "early",
    region: "all",
    anchor: { kind: "gestWeek", n: 8 },
    whyNow: "父亲侧只需知道有材料窗口，不必替医院解释细则。",
    body: "骨架：询问医院/社区需要哪些证件。其他地区请问当地，不在日历里写死截止日期。",
    steps: [],
  },

  // —— 孕中（骨架）——
  {
    id: "mid1-m",
    title: "孕中期常见安排",
    role: "mother",
    type: "science",
    depth: "skeleton",
    stage: "孕中期",
    stageGroup: "mid",
    region: "all",
    anchor: { kind: "gestWeek", n: 22 },
    whyNow: "阶段名提醒：此时常见大排畸等安排，细则以产检医生为准。",
    body: "骨架：孕中期常见系统产检与大排畸窗口。日历不是问诊，不解释报告。以后会加细。",
    steps: [],
  },
  {
    id: "mid1-f",
    title: "孕中期陪同节点",
    role: "father",
    type: "science",
    depth: "skeleton",
    stage: "孕中期",
    stageGroup: "mid",
    region: "all",
    anchor: { kind: "gestWeek", n: 22 },
    whyNow: "让父亲知道「有陪同窗口」，不必现在学完整产程。",
    body: "骨架：询问下一次需要陪同的检查日。不替代医院预约系统。",
    steps: [],
  },

  // —— 孕晚 → 待产（细）——
  {
    id: "l-pack-m",
    title: "待产包怎么放、怎么用",
    role: "mother",
    type: "skill",
    depth: "detailed",
    stage: "孕晚期",
    stageGroup: "late",
    region: "all",
    anchor: { kind: "gestWeek", n: 34 },
    whyNow: "入院当天再找东西会晚。T0 取「最晚也应完成整理」的下限。",
    body: "把「自己用的」和「宝宝用的」分成两个可见口袋，夜间也能摸到。这是整理技能，不是医疗建议。",
    steps: [
      "列出入院可能用到的证件、换洗衣物、卫生用品（不写品牌清单当处方）。",
      "按「进门就要交的 / 待产室用的 / 产后用的」三层装，最外层放证件。",
      "和另一位家长对一次：谁提包、谁拿证件、手机电量谁负责。",
      "把医院位置、夜间入口、停车/出租车预案写在备忘录第一行。",
    ],
    checklist: ["证件在最外层", "夜间能摸到卫生用品", "另一位家长知道包在哪"],
  },
  {
    id: "l-pack-f",
    title: "待产包交接与提包演练",
    role: "father",
    type: "skill",
    depth: "detailed",
    stage: "孕晚期",
    stageGroup: "late",
    region: "all",
    anchor: { kind: "gestWeek", n: 34 },
    whyNow: "陪同入院时父亲常是唯一还能腾出手的人。",
    body: "演练一次从家门到医院门口：包、证件、充电、联系人。不替代医院入院流程。",
    steps: [
      "确认包的位置和最外层证件，能在黑暗中拿到。",
      "保存医院产科急诊入口与夜间电话（以医院公示为准）。",
      "约定：谁开车/叫车、谁抱包、谁负责通知家中老人。",
      "演练充电：两部手机、一条备用线、移动电源在包侧袋。",
    ],
    checklist: ["能独立找到待产包", "急诊入口已保存", "通知名单已约定"],
  },
  {
    id: "l-accompany-f",
    title: "入院陪同：到了医院做什么",
    role: "father",
    type: "skill",
    depth: "detailed",
    stage: "待产窗口",
    stageGroup: "late",
    region: "all",
    anchor: { kind: "gestWeek", n: 38 },
    whyNow: "窗口下限：预产期前就要会走流程，而不是临场问护士。",
    body: "陪同是流程与安抚，不是替医护做判断。红旗症状出现时直接去医院，不在日历里自我诊断。",
    steps: [
      "到院先问分诊/导医：产科急诊还是门诊，按指示走，不争论通道。",
      "递证件与产检本，回答「破水/见红/宫缩间隔」等护士提问（只陈述观察，不自行下诊断）。",
      "管后勤：水杯、外套、充电、记录医嘱时间；不围堵产床。",
      "若被请出待产室：站在可被叫到的位置，保持手机响铃。",
    ],
    checklist: ["知道分诊怎么问", "产检本在手", "手机外放/响铃已开"],
  },
  {
    id: "l-breathe-m",
    title: "呼吸与用力：先建立认知",
    role: "mother",
    type: "skill",
    depth: "detailed",
    stage: "孕晚期",
    stageGroup: "late",
    region: "all",
    anchor: { kind: "gestWeek", n: 36 },
    whyNow: "产房指令以现场医护为准；提前只建立「有人会带你呼吸」的肌肉记忆。",
    body: "本条是认知预习，明确不替代产房指令。现场听助产士/医生，不按视频次数「练到标准」。",
    steps: [
      "了解：宫缩时常见「放松肩颈 + 缓慢呼气」，不是憋气较劲。",
      "和伴侣约定口令：只重复医护刚刚说的那句，不另发明指令。",
      "标红：持续剧烈腹痛、大量出血、胎动显著减少等应立即就医（红旗），不要在家用呼吸法硬扛。",
    ],
    checklist: ["已和伴侣约定「只重复医护口令」", "已知红旗要去医院而不是继续练呼吸"],
    highRisk: true,
  },
  {
    id: "l-labor-m",
    title: "分娩常见过程（概述）",
    role: "mother",
    type: "science",
    depth: "detailed",
    stage: "待产窗口",
    stageGroup: "late",
    region: "all",
    anchor: { kind: "gestWeek", n: 38 },
    whyNow: "减少「完全没听过名词」的惊吓；不是预测你的产程。",
    body: "个体差异极大。以下为常见名词扫盲，不判断你属于哪一种、也不建议手术或用药。",
    steps: [
      "潜伏期 / 活跃期：宫缩逐渐密、宫颈变化，时间因人而异，以医院评估为准。",
      "第二产程：有「用力」相关指导时，听现场指令。",
      "胎盘娩出与产后观察：医护会监测出血等，家属配合记录时间即可。",
      "任何方案（顺产/剖宫产/镇痛）由医患沟通决定，日历不站队。",
    ],
    highRisk: true,
  },
  {
    id: "l-labor-f",
    title: "分娩过程里父亲可以做什么",
    role: "father",
    type: "science",
    depth: "detailed",
    stage: "待产窗口",
    stageGroup: "late",
    region: "all",
    anchor: { kind: "gestWeek", n: 38 },
    whyNow: "陪产不是指挥，是减少混乱。",
    body: "你的任务是传递信息、递水递衣、执行医护让家属做的事。不代替问诊。",
    steps: [
      "记下入院时间、破水/见红的大致观察（若有），供分诊询问。",
      "不转发吓人视频；只重复医护刚说的句子。",
      "需要签字时：看清是什么文件，不替医生解释风险。",
    ],
    highRisk: true,
  },
  {
    id: "l-hospital-when-m",
    title: "何时该去医院（红旗）",
    role: "mother",
    type: "science",
    depth: "detailed",
    stage: "待产窗口",
    stageGroup: "late",
    region: "all",
    anchor: { kind: "gestWeek", n: 37 },
    whyNow: "「最早需要知道红旗」的日子早于预产期当天。",
    body: "以下是应当立即就医或按产检医院嘱咐前往的警示信号方向，不是诊断标准。是否「真的临产」由医院判断。",
    steps: [
      "规律宫缩逐渐加密、无法说话走过；或产检医生已交代的「该去」条件。",
      "阴道流液/见红量让你担心时，不要在家观察太久——去医院让医护看。",
      "胎动显著减少、持续剧烈腹痛、头痛视物模糊、严重水肿等：急诊，不在日历里等下一节拍。",
      "急救：拨打当地急救电话。日历不提供自行处理步骤。",
    ],
    highRisk: true,
  },
  {
    id: "l-hospital-when-f",
    title: "护送去医院的判断（红旗）",
    role: "father",
    type: "science",
    depth: "detailed",
    stage: "待产窗口",
    stageGroup: "late",
    region: "all",
    anchor: { kind: "gestWeek", n: 37 },
    whyNow: "夜间护送常常是父亲的 T0。",
    body: "不确定就去医院，而不是在群里投票。日历不教你「再等一等」。",
    steps: [
      "若对方说「不对劲」，启动待产包与交通预案，而不是先辩论是不是假宫缩。",
      "大量出血、意识改变、抽搐、呼吸困难：打急救电话，不要自己开车硬送（视现场安全）。",
      "到达后把观察时间线交给医护，不要自行下诊断。",
    ],
    highRisk: true,
  },
  {
    id: "l-docs-m",
    title: "证件与待产包清单",
    role: "mother",
    type: "other",
    depth: "detailed",
    stage: "孕晚期",
    stageGroup: "late",
    region: "all",
    anchor: { kind: "gestWeek", n: 32 },
    whyNow: "行政类窗口不能错过：T0 设在「清单应已齐」的下限日。",
    body: "清单用于勾选准备，具体以入住医院书面要求为准。",
    checklist: [
      "身份证",
      "医保卡/电子凭证（按当地）",
      "产检手册 / 检查报告复印件或清晰照片",
      "住院所需现金/支付方式（按医院）",
      "换洗衣物与卫生用品",
      "充电器与备用衣",
    ],
  },
  {
    id: "l-docs-f",
    title: "陪同证件与后勤清单",
    role: "father",
    type: "other",
    depth: "detailed",
    stage: "孕晚期",
    stageGroup: "late",
    region: "all",
    anchor: { kind: "gestWeek", n: 32 },
    whyNow: "父亲常负责「家里还有没有第二套证件」。",
    body: "你自己的证件也可能要用于陪护登记，提前问医院。",
    checklist: [
      "自己的身份证",
      "知道产检本在哪",
      "交通预案（夜间）",
      "家中老人/宠物临时安排",
      "单位请假话术已准备（非法律意见）",
    ],
  },
  {
    id: "l-sh-docs-m",
    title: "上海：地方材料提示",
    role: "mother",
    type: "other",
    depth: "detailed",
    stage: "孕晚期",
    stageGroup: "late",
    region: "shanghai",
    anchor: { kind: "gestWeek", n: 30 },
    whyNow: "上海用户才展示地方材料意识，仍以当年社区/医院公示为准。",
    body: "上海可能涉及生育登记、医保结算、社区办理类材料。本条只提示「去核对其年窗口」，不写死截止日期，也不替代政务大厅。",
    steps: [
      "打开社区事务受理中心 / 随申办等官方入口，核对「生育相关」当前材料清单。",
      "问清住院医院对医保、发票、出院带药结算的要求（仍非处方）。",
      "把官方页面截图放进待产包证件层。",
    ],
    checklist: ["已核对其年官方材料清单", "医院结算口径已口头确认"],
  },
  {
    id: "l-sh-docs-f",
    title: "上海：陪同办理意识",
    role: "father",
    type: "other",
    depth: "detailed",
    stage: "孕晚期",
    stageGroup: "late",
    region: "shanghai",
    anchor: { kind: "gestWeek", n: 30 },
    whyNow: "材料窗口常需双方证件。",
    body: "核对是否需要你的证件、户口或关系材料。以社区当年公示为准。",
    checklist: ["已问社区是否需要男方材料", "复印件/照片已备份"],
  },

  // —— 新生儿～1 岁（细）——
  {
    id: "n-burp-m",
    title: "拍嗝：姿势与停止时机",
    role: "mother",
    type: "skill",
    depth: "detailed",
    stage: "新生儿",
    stageGroup: "y0",
    region: "all",
    anchor: { kind: "ageMonths", n: 0 },
    whyNow: "喂养开始就会用到，T0 取出生当日下限。",
    body: "拍嗝是照料技能。吐奶量、精神、发热等异常应就医，不在家判断病因。",
    steps: [
      "喂完竖直靠肩或坐抱，下巴托稳，手掌空心轻拍后背。",
      "不必追求「必须打出响嗝」；观察是否仍不适、是否频繁喷吐。",
      "呛咳、面色改变、呼吸异常：停下并按急救路径处理/就医，不要加力拍打。",
    ],
    checklist: ["能独立竖直抱稳", "知道异常应就医而不是加力拍"],
    highRisk: true,
  },
  {
    id: "n-burp-f",
    title: "拍嗝：夜班也能上手",
    role: "father",
    type: "skill",
    depth: "detailed",
    stage: "新生儿",
    stageGroup: "y0",
    region: "all",
    anchor: { kind: "ageMonths", n: 0 },
    whyNow: "夜班常轮到父亲，T0 与出生对齐。",
    body: "同一套姿势，强调可交接。非问诊。",
    steps: [
      "让另一位家长看你做一遍，确认托颈手法。",
      "准备吐奶巾，拍完再放下侧卧/仰睡按睡眠安全条。",
      "不要为了拍出嗝而颠簸或按压腹部。",
    ],
    checklist: ["已在清醒时演练一次", "知道不按压腹部"],
  },
  {
    id: "n-feed-m",
    title: "喂养姿势 / 冲奶流程意识",
    role: "mother",
    type: "skill",
    depth: "detailed",
    stage: "新生儿",
    stageGroup: "y0",
    region: "all",
    anchor: { kind: "ageMonths", n: 0 },
    whyNow: "喂养从出生就开始。冲调比例以配方说明与医护指导为准，日历不写剂量。",
    body: "本条只练「姿势与流程意识」。禁止在日历里写毫升、勺数、药物。",
    steps: [
      "哺乳：孩子口含乳晕、鼻尖可呼吸、身体贴紧；疼痛持续应求助国际认证哺乳顾问或医院，不自行忍。",
      "配方：洗手、清洁器具、按罐上说明与医生指导冲调——此处不重复配方数字。",
      "喂时稍倾斜奶瓶充满奶嘴，减少空吸；不把孩子平躺喂。",
      "剩余奶液是否弃去：遵循配方说明与医院宣教，不在此发明规则。",
    ],
    checklist: ["姿势已对照医院宣教", "不把婴儿平躺喂瓶"],
    highRisk: true,
  },
  {
    id: "n-feed-f",
    title: "冲奶与交接（不写剂量）",
    role: "father",
    type: "skill",
    depth: "detailed",
    stage: "新生儿",
    stageGroup: "y0",
    region: "all",
    anchor: { kind: "ageMonths", n: 0 },
    whyNow: "夜奶交接是父亲高频技能。",
    body: "流程可练，剂量不写。以罐装说明和医护为准。",
    steps: [
      "固定清洁—冲调—温度试腕—喂—拍嗝—记录时间（记录不是病历诊断）。",
      "温度只以「不烫腕」为家庭习惯，有疑问问护士，不依赖社交软件口诀。",
      "与另一位家长用同一套记录位置，避免重复喂。",
    ],
    checklist: ["夜班流程能独立走完（不含自拟配方）", "记录位置已约定"],
  },
  {
    id: "n-choke-m",
    title: "呛奶急救演练（意识）",
    role: "mother",
    type: "skill",
    depth: "detailed",
    stage: "新生儿",
    stageGroup: "y0",
    region: "all",
    anchor: { kind: "ageMonths", n: 0 },
    whyNow: "演练必须发生在第一次独自喂养之前。",
    body: "本条只要求你去学官方急救课程/医院宣教里的婴儿气道方法，并知道何时打急救电话。日历不图解按压次数，以免错教。",
    steps: [
      "报名或回看医院/红十字等权威来源的婴儿气道梗阻宣教（来源待法务确认）。",
      "家中约定：一旦面色/呼吸不对，一人打急救电话，一人按刚学的宣教做。",
      "日常预防：不平躺喂、拍嗝、睡眠仰卧（见睡眠安全条）。",
    ],
    checklist: ["已看过权威气道梗阻宣教", "急救电话入口已放主屏"],
    highRisk: true,
  },
  {
    id: "n-choke-f",
    title: "呛奶急救演练（父亲）",
    role: "father",
    type: "skill",
    depth: "detailed",
    stage: "新生儿",
    stageGroup: "y0",
    region: "all",
    anchor: { kind: "ageMonths", n: 0 },
    whyNow: "独自夜班前必须有演练意识。",
    body: "与母亲条相同：学权威宣教，不在此发明手法。",
    steps: [
      "和另一位家长同一套口令：先打电话还是先处理，按急救调度指示。",
      "不把「拍后背」理解成用力拍打胸部。细节只以课程为准。",
    ],
    checklist: ["已完成一次共同演练（课程动作）", "知道拨打急救电话"],
    highRisk: true,
  },
  {
    id: "n-sleep-m",
    title: "安抚入睡（非睡眠训练课）",
    role: "mother",
    type: "skill",
    depth: "detailed",
    stage: "新生儿",
    stageGroup: "y0",
    region: "all",
    anchor: { kind: "ageMonths", n: 1 },
    whyNow: "满月前后昼夜颠倒常见，技能是安抚而非「训练睡整晚」。",
    body: "安全睡姿优先于「睡得久」。不推荐任何让婴儿俯卧无人看管的安抚。",
    steps: [
      "喂养/换尿布后，降低光线与声音，竖直拍嗝再放下。",
      "放下时仰卧、单独睡眠空间，无软枕松毯（见睡眠安全科普）。",
      "持续高声哭、发热、精神差：评估就医，不把哭闹都当成「性格」。",
    ],
    checklist: ["能在仰卧前提下完成一次安抚流程"],
    highRisk: true,
  },
  {
    id: "n-sleep-f",
    title: "夜班安抚交接",
    role: "father",
    type: "skill",
    depth: "detailed",
    stage: "新生儿",
    stageGroup: "y0",
    region: "all",
    anchor: { kind: "ageMonths", n: 1 },
    whyNow: "减少两人同时起来的混乱。",
    body: "约定轮次，不比赛谁更能逗醒孩子。",
    steps: [
      "白班把尿裤、包巾放在同一侧，夜班摸黑能拿到。",
      "安抚失败就换人，而不是叠加更多刺激。",
      "绝不让婴儿趴睡作为「最后办法」。",
    ],
    checklist: ["夜班物品路径已固定", "已约定不使用趴睡"],
  },
  {
    id: "n-food-m",
    title: "辅食添加手法（约 6 月龄窗口）",
    role: "mother",
    type: "skill",
    depth: "detailed",
    stage: "婴儿",
    stageGroup: "y0",
    region: "all",
    anchor: { kind: "ageMonths", n: 6 },
    whyNow: "辅食窗口下限约 6 月龄（个体以儿保为准）。",
    body: "手法是坐稳、勺喂、观察过敏与窒息风险。不写食谱剂量，不替代儿保。",
    steps: [
      "孩子能较稳坐、对食物有兴趣等准备信号——是否开始问儿保医生。",
      "直立坐姿，成人一勺一勺，不边走边喂，不把食物当安抚塞进口。",
      "一次引入一种新食物的家庭习惯来自宣教，过敏疑似停该食物并就医，不当病历记录在标签里。",
      "圆形硬滑食物窒息风险高：家庭回避策略问儿保，不在此列「可以吃的清单」。",
    ],
    checklist: ["座位与勺已准备", "知道疑似过敏/呛咳要停并就医"],
    highRisk: true,
  },
  {
    id: "n-food-f",
    title: "辅食：父亲可接手的喂法",
    role: "father",
    type: "skill",
    depth: "detailed",
    stage: "婴儿",
    stageGroup: "y0",
    region: "all",
    anchor: { kind: "ageMonths", n: 6 },
    whyNow: "周末白天常由父亲喂。",
    body: "同一安全原则，强调不竞赛「谁喂得多」。",
    steps: [
      "问清今天是否新食物、上次是否有异常，不自行加调味。",
      "保持坐姿，不把孩子仰面灌。",
      "进食中不玩手机，观察呛咳。",
    ],
    checklist: ["能按约定完成一餐喂养（无自拟食谱）"],
  },
  {
    id: "n-jaundice-m",
    title: "黄疸：观察什么、何时问医生",
    role: "mother",
    type: "science",
    depth: "detailed",
    stage: "新生儿",
    stageGroup: "y0",
    region: "all",
    anchor: { kind: "ageMonths", n: 0 },
    whyNow: "黄疸观察窗口从出生即开始。",
    body: "黄染进展、精神吃奶、大便颜色等变化应联系医院/儿保，不在家用拍照滤镜判断数值。日历无胆红素阈值。",
    steps: [
      "出院时问清：出现什么情况要返院（以出院医嘱为准）。",
      "日常：吃奶、清醒、尿布次数作为「精神与摄入」的粗观察，异常即问医生。",
      "不自行停喂、不晒太阳替代医疗、不买非处方「退黄」偏方。",
    ],
    highRisk: true,
  },
  {
    id: "n-jaundice-f",
    title: "黄疸：夜班观察交接",
    role: "father",
    type: "science",
    depth: "detailed",
    stage: "新生儿",
    stageGroup: "y0",
    region: "all",
    anchor: { kind: "ageMonths", n: 0 },
    whyNow: "夜班发现异常常由父亲打电话。",
    body: "会描述「吃奶、尿布、精神」即可，不进行诊断。",
    highRisk: true,
    steps: [
      "把出院须知拍在相册固定相册夹。",
      "异常时打医院电话或去急诊，而不是等早班再看。",
    ],
  },
  {
    id: "n-vax-m",
    title: "疫苗在防什么（不是接种医嘱）",
    role: "mother",
    type: "science",
    depth: "detailed",
    stage: "婴儿",
    stageGroup: "y0",
    region: "all",
    anchor: { kind: "ageMonths", n: 2 },
    whyNow: "免疫规划针次从早月龄开始，科普提前到窗口下限。",
    body: "解释「为何要去接种点」，具体针次、禁忌、是否可打由接种门诊决定。不写疫苗商品名剂量。",
    steps: [
      "国家免疫规划保护的是社区里仍可能出现的传染病，不是「可选手工课」。",
      "发热、过敏史等能否接种：只问门诊医生。",
      "接种后观察按门诊要求；家庭标签可用「疫苗后观察」，不当病历。",
    ],
  },
  {
    id: "n-vax-f",
    title: "陪打疫苗：父亲要知道的边界",
    role: "father",
    type: "science",
    depth: "detailed",
    stage: "婴儿",
    stageGroup: "y0",
    region: "all",
    anchor: { kind: "ageMonths", n: 2 },
    whyNow: "常由父亲请假排队。",
    body: "带接种本、带问诊信息，不在现场要求加打或改程序。",
    steps: [
      "出发前：接种本、家长证件（按当地）。",
      "现场：如实说近期发热/用药（药名由家长自己掌握，日历不推荐药）。",
      "回家后按门诊观察，异常就医。",
    ],
  },
  {
    id: "n-foodwhy-m",
    title: "辅食窗口为何约 6 月龄",
    role: "mother",
    type: "science",
    depth: "detailed",
    stage: "婴儿",
    stageGroup: "y0",
    region: "all",
    anchor: { kind: "ageMonths", n: 5 },
    whyNow: "T-14 起需要理解「为什么是现在」，避免过早或过晚的家庭口口相传。",
    body: "约 6 月龄是常见起始讨论点，是否开始以儿保评估为准。过早添加或延迟过久都不要由短视频决定。",
    steps: [
      "铁等营养素需求上升是教材里常见理由——细节以权威儿保材料为准（来源待确认）。",
      "过敏家族史不等于自行决定「永久不添加某类」；问医生。",
    ],
  },
  {
    id: "n-foodwhy-f",
    title: "辅食窗口：别被短视频带偏",
    role: "father",
    type: "science",
    depth: "detailed",
    stage: "婴儿",
    stageGroup: "y0",
    region: "all",
    anchor: { kind: "ageMonths", n: 5 },
    whyNow: "父亲常在群里看到互相矛盾的月龄口诀。",
    body: "以儿保预约为准。日历不给食谱。",
    steps: ["把下一次儿保日期放进家庭日历。", "不把「隔壁孩子已经吃了」当成医嘱。"],
  },
  {
    id: "n-safesleep-m",
    title: "睡眠安全",
    role: "mother",
    type: "science",
    depth: "detailed",
    stage: "新生儿",
    stageGroup: "y0",
    region: "all",
    anchor: { kind: "ageMonths", n: 0 },
    whyNow: "睡眠环境从回家第一夜就需要。",
    body: "常见宣教方向：仰卧、单独睡在符合标准的睡眠空间、避免柔软遮盖物与过热。同床共睡风险需按权威指南理解，不在此鼓励。",
    steps: [
      "每次放下都检查：仰卧、面部无遮挡。",
      "不用普通枕头、松软毛毯当新生儿寝具。",
      "烟雾环境、过热、生病时更应提高警惕并咨询医生。",
    ],
    highRisk: true,
  },
  {
    id: "n-safesleep-f",
    title: "睡眠安全（夜班复查）",
    role: "father",
    type: "science",
    depth: "detailed",
    stage: "新生儿",
    stageGroup: "y0",
    region: "all",
    anchor: { kind: "ageMonths", n: 0 },
    whyNow: "半夜放下时最容易图方便。",
    body: "再困也把孩子仰卧放回指定睡眠空间。",
    highRisk: true,
    steps: ["沙发、成人枕、斜靠喂睡后无人看管都是高风险场景——避免。", "发现趴着立即改为仰卧并保持观察，异常就医。"],
  },
  {
    id: "n-vaxbook-m",
    title: "接种本与预约口径",
    role: "mother",
    type: "other",
    depth: "detailed",
    stage: "新生儿",
    stageGroup: "y0",
    region: "all",
    anchor: { kind: "ageMonths", n: 0 },
    whyNow: "行政窗口从出院建册开始。",
    body: "其他地区：按国家免疫规划共性 + 问当地接种点。不写死外地截止日。",
    checklist: ["接种本或电子册入口已知", "已问清本社区预约方式", "下一次窗口已记在日历（以门诊为准）"],
  },
  {
    id: "n-vaxbook-f",
    title: "接种预约谁去排队",
    role: "father",
    type: "other",
    depth: "detailed",
    stage: "新生儿",
    stageGroup: "y0",
    region: "all",
    anchor: { kind: "ageMonths", n: 0 },
    whyNow: "请假窗口需要提前知道。",
    body: "约定谁持本、谁请假。预约失败就问门诊，不改用非官方黄牛。",
    checklist: ["持本人已约定", "预约渠道已保存"],
  },
  {
    id: "n-vax-sh-m",
    title: "上海接种程序骨架",
    role: "mother",
    type: "other",
    depth: "detailed",
    stage: "婴儿",
    stageGroup: "y0",
    region: "shanghai",
    anchor: { kind: "ageMonths", n: 1 },
    whyNow: "上海用户提示地方程序入口，仍以当年疾控/社区为准。",
    body: "打开上海疾控/社区卫生中心公示的免疫规划程序，把「下一针名称」抄到日历备注。本产品不复制官方时间表全文，以免过期。",
    steps: ["收藏官方程序页。", "以社区预约短信/系统为准，而不是家长群截图。"],
  },
  {
    id: "n-vax-sh-f",
    title: "上海：陪同接种入口",
    role: "father",
    type: "other",
    depth: "detailed",
    stage: "婴儿",
    stageGroup: "y0",
    region: "shanghai",
    anchor: { kind: "ageMonths", n: 1 },
    whyNow: "地方预约系统常需提前操作。",
    body: "确认随申办/社区系统当前入口。过期链接以官方为准。",
    checklist: ["预约入口已验证能打开"],
  },

  // —— 1 岁 → 7 岁（骨架）——
  {
    id: "t-toilet-m",
    title: "如厕技能：这类准备存在",
    role: "mother",
    type: "skill",
    depth: "skeleton",
    stage: "幼儿",
    stageGroup: "y1to7",
    region: "all",
    anchor: { kind: "ageMonths", n: 24 },
    whyNow: "约 2 岁前后家庭开始讨论如厕，仅作阶段入口。",
    body: "骨架：存在如厕准备这类技能。不写长教程。以后会加细。",
    steps: [],
  },
  {
    id: "t-toilet-f",
    title: "如厕协同（骨架）",
    role: "father",
    type: "skill",
    depth: "skeleton",
    stage: "幼儿",
    stageGroup: "y1to7",
    region: "all",
    anchor: { kind: "ageMonths", n: 24 },
    whyNow: "需要两位家长同一套口径。",
    body: "骨架：约定不惩罚、不比较。细稿未写。",
    steps: [],
  },
  {
    id: "t-sep-m",
    title: "入园分离：这类技能存在",
    role: "mother",
    type: "skill",
    depth: "skeleton",
    stage: "幼儿",
    stageGroup: "y1to7",
    region: "all",
    anchor: { kind: "ageYears", n: 3 },
    whyNow: "入园年龄窗口各地不同，T0 取常见下限意识日。",
    body: "骨架：存在分离焦虑与短告别这类准备。以后会加细。",
    steps: [],
  },
  {
    id: "t-sep-f",
    title: "送园的人怎么告别（骨架）",
    role: "father",
    type: "skill",
    depth: "skeleton",
    stage: "幼儿",
    stageGroup: "y1to7",
    region: "all",
    anchor: { kind: "ageYears", n: 3 },
    whyNow: "送园人常常是父亲。",
    body: "骨架：短告别、不偷偷消失的原则以后细写。",
    steps: [],
  },
  {
    id: "t-sep-sci-m",
    title: "分离焦虑常见（一句话）",
    role: "mother",
    type: "science",
    depth: "skeleton",
    stage: "幼儿",
    stageGroup: "y1to7",
    region: "all",
    anchor: { kind: "ageYears", n: 3 },
    whyNow: "阶段科普，不诊断。",
    body: "骨架：入园前后出现哭闹、黏人在发育上常见；持续异常问儿保。以后会加细。",
    steps: [],
  },
  {
    id: "t-sep-sci-f",
    title: "分离焦虑：父亲侧一句话",
    role: "father",
    type: "science",
    depth: "skeleton",
    stage: "幼儿",
    stageGroup: "y1to7",
    region: "all",
    anchor: { kind: "ageYears", n: 3 },
    whyNow: "避免指责「被宠坏」。",
    body: "骨架：哭不等于教养失败。细稿未写。",
    steps: [],
  },
  {
    id: "t-school-sci-m",
    title: "幼小作息（一句话）",
    role: "mother",
    type: "science",
    depth: "skeleton",
    stage: "学龄前",
    stageGroup: "y1to7",
    region: "all",
    anchor: { kind: "ageYears", n: 6 },
    whyNow: "入学前作息调整是阶段名，不是训练营。",
    body: "骨架：小学作息与幼儿园不同，需提前几天适应。以后会加细。",
    steps: [],
  },
  {
    id: "t-school-sci-f",
    title: "幼小作息（父亲）",
    role: "father",
    type: "science",
    depth: "skeleton",
    stage: "学龄前",
    stageGroup: "y1to7",
    region: "all",
    anchor: { kind: "ageYears", n: 6 },
    whyNow: "晚归父亲也要同一套起床口径。",
    body: "骨架：周末补觉与上学日冲突时，优先上学日。细稿未写。",
    steps: [],
  },
  {
    id: "t-kinder-m",
    title: "入园材料窗口",
    role: "mother",
    type: "other",
    depth: "skeleton",
    stage: "幼儿",
    stageGroup: "y1to7",
    region: "all",
    anchor: { kind: "ageYears", n: 3 },
    whyNow: "行政窗口不能错过，只给条目名。",
    body: "骨架：存在体检、预防接种审核、户籍/居住材料等窗口。其他地区请问当地园，不写死截止日期。",
    steps: [],
  },
  {
    id: "t-kinder-f",
    title: "入园材料：谁去跑",
    role: "father",
    type: "other",
    depth: "skeleton",
    stage: "幼儿",
    stageGroup: "y1to7",
    region: "all",
    anchor: { kind: "ageYears", n: 3 },
    whyNow: "请假跑材料常在父亲侧。",
    body: "骨架：问当地园清单。上海用户见地方条。",
    steps: [],
  },
  {
    id: "t-kinder-sh-m",
    title: "上海：入园材料窗口名",
    role: "mother",
    type: "other",
    depth: "skeleton",
    stage: "幼儿",
    stageGroup: "y1to7",
    region: "shanghai",
    anchor: { kind: "ageYears", n: 3 },
    whyNow: "上海可点名本地窗口意识，仍以当年教育局为准。",
    body: "骨架：关注区教育局当年入园报名与信息登记窗口。本条不复制当年日期。",
    steps: [],
  },
  {
    id: "t-school-m",
    title: "入学材料窗口",
    role: "mother",
    type: "other",
    depth: "skeleton",
    stage: "小学低年级",
    stageGroup: "y1to7",
    region: "all",
    anchor: { kind: "ageYears", n: 6 },
    whyNow: "入学登记有窗口下限。",
    body: "骨架：存在入学信息登记/材料提交。其他地区问当地校/教育局。",
    steps: [],
  },
  {
    id: "t-school-sh-f",
    title: "上海：入学登记窗口名",
    role: "father",
    type: "other",
    depth: "skeleton",
    stage: "小学低年级",
    stageGroup: "y1to7",
    region: "shanghai",
    anchor: { kind: "ageYears", n: 6 },
    whyNow: "地方行政常需父亲证件。",
    body: "骨架：关注「入学信息登记」等当年官方名称。不写死日期。",
    steps: [],
  },
];

export function itemById(id) {
  return CATALOG.find((x) => x.id === id);
}

export const TYPE_LABEL = { skill: "技能", science: "科普", other: "其他" };
export const ROLE_LABEL = { father: "给父亲", mother: "给母亲" };
export const DEPTH_LABEL = { detailed: "细", skeleton: "骨架" };
